version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: changeme
    restart: on-failure
    volumes:
      - ${PWD}/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database:
